version: '3.3'
volumes:
  data:
services:
  db:
    image: mysql:5.6
    container_name: mysql_stock
    ports:
      - "3306:3306"
    volumes:
      - data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=12345
      - MYSQL_DATABASE=teste
  app:
    image: stockdocker
    container_name: api_stock
    links:
      - db
    ports:
      - 8089:8080
